// flow-typed signature: c7a104b8adcfafd5dd938856a05b8d5f
// flow-typed version: <<STUB>>/googleapis_v^13.0.0/flow_v0.30.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'googleapis'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'googleapis' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'googleapis/v1' {
  declare module.exports: any;
}

declare module 'googleapis/v1.2' {
  declare module.exports: any;
}

declare module 'googleapis/v1.3' {
  declare module.exports: any;
}

declare module 'googleapis/v1.4' {
  declare module.exports: any;
}

declare module 'googleapis/v2beta1' {
  declare module.exports: any;
}

declare module 'googleapis/v1.1' {
  declare module.exports: any;
}

declare module 'googleapis/v1' {
  declare module.exports: any;
}

declare module 'googleapis/v2.0' {
  declare module.exports: any;
}

declare module 'googleapis/datatransfer_v1' {
  declare module.exports: any;
}

declare module 'googleapis/directory_v1' {
  declare module.exports: any;
}

declare module 'googleapis/reports_v1' {
  declare module.exports: any;
}

declare module 'googleapis/v1.2' {
  declare module.exports: any;
}

declare module 'googleapis/v1.3' {
  declare module.exports: any;
}

declare module 'googleapis/v1.4' {
  declare module.exports: any;
}

declare module 'googleapis/v4.1' {
  declare module.exports: any;
}

declare module 'googleapis/v2.4' {
  declare module.exports: any;
}

declare module 'googleapis/v3' {
  declare module.exports: any;
}

declare module 'googleapis/v4' {
  declare module.exports: any;
}

declare module 'googleapis/v1' {
  declare module.exports: any;
}

declare module 'googleapis/v1.1' {
  declare module.exports: any;
}

declare module 'googleapis/v1' {
  declare module.exports: any;
}

declare module 'googleapis/v2' {
  declare module.exports: any;
}

declare module 'googleapis/v1' {
  declare module.exports: any;
}

declare module 'googleapis/v1beta4' {
  declare module.exports: any;
}

declare module 'googleapis/v1beta5' {
  declare module.exports: any;
}

declare module 'googleapis/v1' {
  declare module.exports: any;
}

declare module 'googleapis/v1' {
  declare module.exports: any;
}

declare module 'googleapis/v2' {
  declare module.exports: any;
}

declare module 'googleapis/v2' {
  declare module.exports: any;
}

declare module 'googleapis/v3' {
  declare module.exports: any;
}

declare module 'googleapis/v1' {
  declare module.exports: any;
}

declare module 'googleapis/v3' {
  declare module.exports: any;
}

declare module 'googleapis/v2' {
  declare module.exports: any;
}

declare module 'googleapis/v1' {
  declare module.exports: any;
}

declare module 'googleapis/v1' {
  declare module.exports: any;
}

declare module 'googleapis/v1' {
  declare module.exports: any;
}

declare module 'googleapis/v2' {
  declare module.exports: any;
}

declare module 'googleapis/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/v2beta2' {
  declare module.exports: any;
}

declare module 'googleapis/v1' {
  declare module.exports: any;
}

declare module 'googleapis/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/v1' {
  declare module.exports: any;
}

declare module 'googleapis/alpha' {
  declare module.exports: any;
}

declare module 'googleapis/beta' {
  declare module.exports: any;
}

declare module 'googleapis/vm_alpha' {
  declare module.exports: any;
}

declare module 'googleapis/vm_beta' {
  declare module.exports: any;
}

declare module 'googleapis/alpha' {
  declare module.exports: any;
}

declare module 'googleapis/beta' {
  declare module.exports: any;
}

declare module 'googleapis/v1' {
  declare module.exports: any;
}

declare module 'googleapis/v2' {
  declare module.exports: any;
}

declare module 'googleapis/v1' {
  declare module.exports: any;
}

declare module 'googleapis/v2' {
  declare module.exports: any;
}

declare module 'googleapis/v2sandbox' {
  declare module.exports: any;
}

declare module 'googleapis/v1' {
  declare module.exports: any;
}

declare module 'googleapis/v1b3' {
  declare module.exports: any;
}

declare module 'googleapis/v1' {
  declare module.exports: any;
}

declare module 'googleapis/v1alpha1' {
  declare module.exports: any;
}

declare module 'googleapis/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/v1' {
  declare module.exports: any;
}

declare module 'googleapis/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/v1beta2' {
  declare module.exports: any;
}

declare module 'googleapis/v1beta3' {
  declare module.exports: any;
}

declare module 'googleapis/v2' {
  declare module.exports: any;
}

declare module 'googleapis/v2.2' {
  declare module.exports: any;
}

declare module 'googleapis/v2.3' {
  declare module.exports: any;
}

declare module 'googleapis/v2.4' {
  declare module.exports: any;
}

declare module 'googleapis/v2.5' {
  declare module.exports: any;
}

declare module 'googleapis/v2.5beta1' {
  declare module.exports: any;
}

declare module 'googleapis/v2.6' {
  declare module.exports: any;
}

declare module 'googleapis/v1' {
  declare module.exports: any;
}

declare module 'googleapis/v1' {
  declare module.exports: any;
}

declare module 'googleapis/v2beta1' {
  declare module.exports: any;
}

declare module 'googleapis/v1' {
  declare module.exports: any;
}

declare module 'googleapis/v2' {
  declare module.exports: any;
}

declare module 'googleapis/v2' {
  declare module.exports: any;
}

declare module 'googleapis/v3' {
  declare module.exports: any;
}

declare module 'googleapis/v1' {
  declare module.exports: any;
}

declare module 'googleapis/v1' {
  declare module.exports: any;
}

declare module 'googleapis/v1' {
  declare module.exports: any;
}

declare module 'googleapis/v2' {
  declare module.exports: any;
}

declare module 'googleapis/v1' {
  declare module.exports: any;
}

declare module 'googleapis/v1configuration' {
  declare module.exports: any;
}

declare module 'googleapis/v1management' {
  declare module.exports: any;
}

declare module 'googleapis/v1' {
  declare module.exports: any;
}

declare module 'googleapis/v1alpha2' {
  declare module.exports: any;
}

declare module 'googleapis/v1beta2' {
  declare module.exports: any;
}

declare module 'googleapis/v1' {
  declare module.exports: any;
}

declare module 'googleapis/v1' {
  declare module.exports: any;
}

declare module 'googleapis/v1' {
  declare module.exports: any;
}

declare module 'googleapis/v1' {
  declare module.exports: any;
}

declare module 'googleapis/v3' {
  declare module.exports: any;
}

declare module 'googleapis/v1' {
  declare module.exports: any;
}

declare module 'googleapis/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/v1' {
  declare module.exports: any;
}

declare module 'googleapis/v2beta1' {
  declare module.exports: any;
}

declare module 'googleapis/v1' {
  declare module.exports: any;
}

declare module 'googleapis/v3' {
  declare module.exports: any;
}

declare module 'googleapis/v1' {
  declare module.exports: any;
}

declare module 'googleapis/v2' {
  declare module.exports: any;
}

declare module 'googleapis/v1' {
  declare module.exports: any;
}

declare module 'googleapis/v2' {
  declare module.exports: any;
}

declare module 'googleapis/v2' {
  declare module.exports: any;
}

declare module 'googleapis/v1' {
  declare module.exports: any;
}

declare module 'googleapis/v1' {
  declare module.exports: any;
}

declare module 'googleapis/v1' {
  declare module.exports: any;
}

declare module 'googleapis/v1' {
  declare module.exports: any;
}

declare module 'googleapis/v1.2' {
  declare module.exports: any;
}

declare module 'googleapis/v1.3' {
  declare module.exports: any;
}

declare module 'googleapis/v1.4' {
  declare module.exports: any;
}

declare module 'googleapis/v1.5' {
  declare module.exports: any;
}

declare module 'googleapis/v1.6' {
  declare module.exports: any;
}

declare module 'googleapis/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/v1' {
  declare module.exports: any;
}

declare module 'googleapis/v1beta1a' {
  declare module.exports: any;
}

declare module 'googleapis/v1beta2' {
  declare module.exports: any;
}

declare module 'googleapis/v1' {
  declare module.exports: any;
}

declare module 'googleapis/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/v1beta2' {
  declare module.exports: any;
}

declare module 'googleapis/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/v1' {
  declare module.exports: any;
}

declare module 'googleapis/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/v1beta2' {
  declare module.exports: any;
}

declare module 'googleapis/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/v4' {
  declare module.exports: any;
}

declare module 'googleapis/v1' {
  declare module.exports: any;
}

declare module 'googleapis/v1' {
  declare module.exports: any;
}

declare module 'googleapis/v1' {
  declare module.exports: any;
}

declare module 'googleapis/v4' {
  declare module.exports: any;
}

declare module 'googleapis/v1' {
  declare module.exports: any;
}

declare module 'googleapis/v1explorer' {
  declare module.exports: any;
}

declare module 'googleapis/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/v1beta3' {
  declare module.exports: any;
}

declare module 'googleapis/v1beta4' {
  declare module.exports: any;
}

declare module 'googleapis/v1' {
  declare module.exports: any;
}

declare module 'googleapis/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/v1beta2' {
  declare module.exports: any;
}

declare module 'googleapis/v1' {
  declare module.exports: any;
}

declare module 'googleapis/v1' {
  declare module.exports: any;
}

declare module 'googleapis/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/v1beta2' {
  declare module.exports: any;
}

declare module 'googleapis/v1' {
  declare module.exports: any;
}

declare module 'googleapis/v1beta3' {
  declare module.exports: any;
}

declare module 'googleapis/v2' {
  declare module.exports: any;
}

declare module 'googleapis/v1' {
  declare module.exports: any;
}

declare module 'googleapis/v1' {
  declare module.exports: any;
}

declare module 'googleapis/v1' {
  declare module.exports: any;
}

declare module 'googleapis/v3' {
  declare module.exports: any;
}

declare module 'googleapis/v3' {
  declare module.exports: any;
}

declare module 'googleapis/v1' {
  declare module.exports: any;
}

declare module 'googleapis/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/v1' {
  declare module.exports: any;
}

declare module 'googleapis/apirequest' {
  declare module.exports: any;
}

declare module 'googleapis/authclient' {
  declare module.exports: any;
}

declare module 'googleapis/computeclient' {
  declare module.exports: any;
}

declare module 'googleapis/jwtclient' {
  declare module.exports: any;
}

declare module 'googleapis/loginticket' {
  declare module.exports: any;
}

declare module 'googleapis/oauth2client' {
  declare module.exports: any;
}

declare module 'googleapis/discovery' {
  declare module.exports: any;
}

declare module 'googleapis/generator_utils' {
  declare module.exports: any;
}

declare module 'googleapis/generator' {
  declare module.exports: any;
}

declare module 'googleapis/googleapis' {
  declare module.exports: any;
}

declare module 'googleapis/pemverifier' {
  declare module.exports: any;
}

declare module 'googleapis/transporters' {
  declare module.exports: any;
}

declare module 'googleapis/utils' {
  declare module.exports: any;
}

declare module 'googleapis/generate' {
  declare module.exports: any;
}

declare module 'googleapis/api-endpoint' {
  declare module.exports: any;
}

declare module 'googleapis/method-partial' {
  declare module.exports: any;
}

declare module 'googleapis/resource-partial' {
  declare module.exports: any;
}

// Filename aliases
declare module 'googleapis/v1.js' {
  declare module.exports: $Exports<'googleapis/v1'>;
}
declare module 'googleapis/v1.2.js' {
  declare module.exports: $Exports<'googleapis/v1.2'>;
}
declare module 'googleapis/v1.3.js' {
  declare module.exports: $Exports<'googleapis/v1.3'>;
}
declare module 'googleapis/v1.4.js' {
  declare module.exports: $Exports<'googleapis/v1.4'>;
}
declare module 'googleapis/v2beta1.js' {
  declare module.exports: $Exports<'googleapis/v2beta1'>;
}
declare module 'googleapis/v1.1.js' {
  declare module.exports: $Exports<'googleapis/v1.1'>;
}
declare module 'googleapis/v1.js' {
  declare module.exports: $Exports<'googleapis/v1'>;
}
declare module 'googleapis/v2.0.js' {
  declare module.exports: $Exports<'googleapis/v2.0'>;
}
declare module 'googleapis/datatransfer_v1.js' {
  declare module.exports: $Exports<'googleapis/datatransfer_v1'>;
}
declare module 'googleapis/directory_v1.js' {
  declare module.exports: $Exports<'googleapis/directory_v1'>;
}
declare module 'googleapis/reports_v1.js' {
  declare module.exports: $Exports<'googleapis/reports_v1'>;
}
declare module 'googleapis/v1.2.js' {
  declare module.exports: $Exports<'googleapis/v1.2'>;
}
declare module 'googleapis/v1.3.js' {
  declare module.exports: $Exports<'googleapis/v1.3'>;
}
declare module 'googleapis/v1.4.js' {
  declare module.exports: $Exports<'googleapis/v1.4'>;
}
declare module 'googleapis/v4.1.js' {
  declare module.exports: $Exports<'googleapis/v4.1'>;
}
declare module 'googleapis/v2.4.js' {
  declare module.exports: $Exports<'googleapis/v2.4'>;
}
declare module 'googleapis/v3.js' {
  declare module.exports: $Exports<'googleapis/v3'>;
}
declare module 'googleapis/v4.js' {
  declare module.exports: $Exports<'googleapis/v4'>;
}
declare module 'googleapis/v1.js' {
  declare module.exports: $Exports<'googleapis/v1'>;
}
declare module 'googleapis/v1.1.js' {
  declare module.exports: $Exports<'googleapis/v1.1'>;
}
declare module 'googleapis/v1.js' {
  declare module.exports: $Exports<'googleapis/v1'>;
}
declare module 'googleapis/v2.js' {
  declare module.exports: $Exports<'googleapis/v2'>;
}
declare module 'googleapis/v1.js' {
  declare module.exports: $Exports<'googleapis/v1'>;
}
declare module 'googleapis/v1beta4.js' {
  declare module.exports: $Exports<'googleapis/v1beta4'>;
}
declare module 'googleapis/v1beta5.js' {
  declare module.exports: $Exports<'googleapis/v1beta5'>;
}
declare module 'googleapis/v1.js' {
  declare module.exports: $Exports<'googleapis/v1'>;
}
declare module 'googleapis/v1.js' {
  declare module.exports: $Exports<'googleapis/v1'>;
}
declare module 'googleapis/v2.js' {
  declare module.exports: $Exports<'googleapis/v2'>;
}
declare module 'googleapis/v2.js' {
  declare module.exports: $Exports<'googleapis/v2'>;
}
declare module 'googleapis/v3.js' {
  declare module.exports: $Exports<'googleapis/v3'>;
}
declare module 'googleapis/v1.js' {
  declare module.exports: $Exports<'googleapis/v1'>;
}
declare module 'googleapis/v3.js' {
  declare module.exports: $Exports<'googleapis/v3'>;
}
declare module 'googleapis/v2.js' {
  declare module.exports: $Exports<'googleapis/v2'>;
}
declare module 'googleapis/v1.js' {
  declare module.exports: $Exports<'googleapis/v1'>;
}
declare module 'googleapis/v1.js' {
  declare module.exports: $Exports<'googleapis/v1'>;
}
declare module 'googleapis/v1.js' {
  declare module.exports: $Exports<'googleapis/v1'>;
}
declare module 'googleapis/v2.js' {
  declare module.exports: $Exports<'googleapis/v2'>;
}
declare module 'googleapis/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/v1beta1'>;
}
declare module 'googleapis/v2beta2.js' {
  declare module.exports: $Exports<'googleapis/v2beta2'>;
}
declare module 'googleapis/v1.js' {
  declare module.exports: $Exports<'googleapis/v1'>;
}
declare module 'googleapis/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/v1beta1'>;
}
declare module 'googleapis/v1.js' {
  declare module.exports: $Exports<'googleapis/v1'>;
}
declare module 'googleapis/alpha.js' {
  declare module.exports: $Exports<'googleapis/alpha'>;
}
declare module 'googleapis/beta.js' {
  declare module.exports: $Exports<'googleapis/beta'>;
}
declare module 'googleapis/vm_alpha.js' {
  declare module.exports: $Exports<'googleapis/vm_alpha'>;
}
declare module 'googleapis/vm_beta.js' {
  declare module.exports: $Exports<'googleapis/vm_beta'>;
}
declare module 'googleapis/alpha.js' {
  declare module.exports: $Exports<'googleapis/alpha'>;
}
declare module 'googleapis/beta.js' {
  declare module.exports: $Exports<'googleapis/beta'>;
}
declare module 'googleapis/v1.js' {
  declare module.exports: $Exports<'googleapis/v1'>;
}
declare module 'googleapis/v2.js' {
  declare module.exports: $Exports<'googleapis/v2'>;
}
declare module 'googleapis/v1.js' {
  declare module.exports: $Exports<'googleapis/v1'>;
}
declare module 'googleapis/v2.js' {
  declare module.exports: $Exports<'googleapis/v2'>;
}
declare module 'googleapis/v2sandbox.js' {
  declare module.exports: $Exports<'googleapis/v2sandbox'>;
}
declare module 'googleapis/v1.js' {
  declare module.exports: $Exports<'googleapis/v1'>;
}
declare module 'googleapis/v1b3.js' {
  declare module.exports: $Exports<'googleapis/v1b3'>;
}
declare module 'googleapis/v1.js' {
  declare module.exports: $Exports<'googleapis/v1'>;
}
declare module 'googleapis/v1alpha1.js' {
  declare module.exports: $Exports<'googleapis/v1alpha1'>;
}
declare module 'googleapis/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/v1beta1'>;
}
declare module 'googleapis/v1.js' {
  declare module.exports: $Exports<'googleapis/v1'>;
}
declare module 'googleapis/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/v1beta1'>;
}
declare module 'googleapis/v1beta2.js' {
  declare module.exports: $Exports<'googleapis/v1beta2'>;
}
declare module 'googleapis/v1beta3.js' {
  declare module.exports: $Exports<'googleapis/v1beta3'>;
}
declare module 'googleapis/v2.js' {
  declare module.exports: $Exports<'googleapis/v2'>;
}
declare module 'googleapis/v2.2.js' {
  declare module.exports: $Exports<'googleapis/v2.2'>;
}
declare module 'googleapis/v2.3.js' {
  declare module.exports: $Exports<'googleapis/v2.3'>;
}
declare module 'googleapis/v2.4.js' {
  declare module.exports: $Exports<'googleapis/v2.4'>;
}
declare module 'googleapis/v2.5.js' {
  declare module.exports: $Exports<'googleapis/v2.5'>;
}
declare module 'googleapis/v2.5beta1.js' {
  declare module.exports: $Exports<'googleapis/v2.5beta1'>;
}
declare module 'googleapis/v2.6.js' {
  declare module.exports: $Exports<'googleapis/v2.6'>;
}
declare module 'googleapis/v1.js' {
  declare module.exports: $Exports<'googleapis/v1'>;
}
declare module 'googleapis/v1.js' {
  declare module.exports: $Exports<'googleapis/v1'>;
}
declare module 'googleapis/v2beta1.js' {
  declare module.exports: $Exports<'googleapis/v2beta1'>;
}
declare module 'googleapis/v1.js' {
  declare module.exports: $Exports<'googleapis/v1'>;
}
declare module 'googleapis/v2.js' {
  declare module.exports: $Exports<'googleapis/v2'>;
}
declare module 'googleapis/v2.js' {
  declare module.exports: $Exports<'googleapis/v2'>;
}
declare module 'googleapis/v3.js' {
  declare module.exports: $Exports<'googleapis/v3'>;
}
declare module 'googleapis/v1.js' {
  declare module.exports: $Exports<'googleapis/v1'>;
}
declare module 'googleapis/v1.js' {
  declare module.exports: $Exports<'googleapis/v1'>;
}
declare module 'googleapis/v1.js' {
  declare module.exports: $Exports<'googleapis/v1'>;
}
declare module 'googleapis/v2.js' {
  declare module.exports: $Exports<'googleapis/v2'>;
}
declare module 'googleapis/v1.js' {
  declare module.exports: $Exports<'googleapis/v1'>;
}
declare module 'googleapis/v1configuration.js' {
  declare module.exports: $Exports<'googleapis/v1configuration'>;
}
declare module 'googleapis/v1management.js' {
  declare module.exports: $Exports<'googleapis/v1management'>;
}
declare module 'googleapis/v1.js' {
  declare module.exports: $Exports<'googleapis/v1'>;
}
declare module 'googleapis/v1alpha2.js' {
  declare module.exports: $Exports<'googleapis/v1alpha2'>;
}
declare module 'googleapis/v1beta2.js' {
  declare module.exports: $Exports<'googleapis/v1beta2'>;
}
declare module 'googleapis/v1.js' {
  declare module.exports: $Exports<'googleapis/v1'>;
}
declare module 'googleapis/v1.js' {
  declare module.exports: $Exports<'googleapis/v1'>;
}
declare module 'googleapis/v1.js' {
  declare module.exports: $Exports<'googleapis/v1'>;
}
declare module 'googleapis/v1.js' {
  declare module.exports: $Exports<'googleapis/v1'>;
}
declare module 'googleapis/v3.js' {
  declare module.exports: $Exports<'googleapis/v3'>;
}
declare module 'googleapis/v1.js' {
  declare module.exports: $Exports<'googleapis/v1'>;
}
declare module 'googleapis/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/v1beta1'>;
}
declare module 'googleapis/v1.js' {
  declare module.exports: $Exports<'googleapis/v1'>;
}
declare module 'googleapis/v2beta1.js' {
  declare module.exports: $Exports<'googleapis/v2beta1'>;
}
declare module 'googleapis/v1.js' {
  declare module.exports: $Exports<'googleapis/v1'>;
}
declare module 'googleapis/v3.js' {
  declare module.exports: $Exports<'googleapis/v3'>;
}
declare module 'googleapis/v1.js' {
  declare module.exports: $Exports<'googleapis/v1'>;
}
declare module 'googleapis/v2.js' {
  declare module.exports: $Exports<'googleapis/v2'>;
}
declare module 'googleapis/v1.js' {
  declare module.exports: $Exports<'googleapis/v1'>;
}
declare module 'googleapis/v2.js' {
  declare module.exports: $Exports<'googleapis/v2'>;
}
declare module 'googleapis/v2.js' {
  declare module.exports: $Exports<'googleapis/v2'>;
}
declare module 'googleapis/v1.js' {
  declare module.exports: $Exports<'googleapis/v1'>;
}
declare module 'googleapis/v1.js' {
  declare module.exports: $Exports<'googleapis/v1'>;
}
declare module 'googleapis/v1.js' {
  declare module.exports: $Exports<'googleapis/v1'>;
}
declare module 'googleapis/v1.js' {
  declare module.exports: $Exports<'googleapis/v1'>;
}
declare module 'googleapis/v1.2.js' {
  declare module.exports: $Exports<'googleapis/v1.2'>;
}
declare module 'googleapis/v1.3.js' {
  declare module.exports: $Exports<'googleapis/v1.3'>;
}
declare module 'googleapis/v1.4.js' {
  declare module.exports: $Exports<'googleapis/v1.4'>;
}
declare module 'googleapis/v1.5.js' {
  declare module.exports: $Exports<'googleapis/v1.5'>;
}
declare module 'googleapis/v1.6.js' {
  declare module.exports: $Exports<'googleapis/v1.6'>;
}
declare module 'googleapis/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/v1beta1'>;
}
declare module 'googleapis/v1.js' {
  declare module.exports: $Exports<'googleapis/v1'>;
}
declare module 'googleapis/v1beta1a.js' {
  declare module.exports: $Exports<'googleapis/v1beta1a'>;
}
declare module 'googleapis/v1beta2.js' {
  declare module.exports: $Exports<'googleapis/v1beta2'>;
}
declare module 'googleapis/v1.js' {
  declare module.exports: $Exports<'googleapis/v1'>;
}
declare module 'googleapis/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/v1beta1'>;
}
declare module 'googleapis/v1beta2.js' {
  declare module.exports: $Exports<'googleapis/v1beta2'>;
}
declare module 'googleapis/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/v1beta1'>;
}
declare module 'googleapis/v1.js' {
  declare module.exports: $Exports<'googleapis/v1'>;
}
declare module 'googleapis/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/v1beta1'>;
}
declare module 'googleapis/v1beta2.js' {
  declare module.exports: $Exports<'googleapis/v1beta2'>;
}
declare module 'googleapis/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/v1beta1'>;
}
declare module 'googleapis/v4.js' {
  declare module.exports: $Exports<'googleapis/v4'>;
}
declare module 'googleapis/v1.js' {
  declare module.exports: $Exports<'googleapis/v1'>;
}
declare module 'googleapis/v1.js' {
  declare module.exports: $Exports<'googleapis/v1'>;
}
declare module 'googleapis/v1.js' {
  declare module.exports: $Exports<'googleapis/v1'>;
}
declare module 'googleapis/v4.js' {
  declare module.exports: $Exports<'googleapis/v4'>;
}
declare module 'googleapis/v1.js' {
  declare module.exports: $Exports<'googleapis/v1'>;
}
declare module 'googleapis/v1explorer.js' {
  declare module.exports: $Exports<'googleapis/v1explorer'>;
}
declare module 'googleapis/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/v1beta1'>;
}
declare module 'googleapis/v1beta3.js' {
  declare module.exports: $Exports<'googleapis/v1beta3'>;
}
declare module 'googleapis/v1beta4.js' {
  declare module.exports: $Exports<'googleapis/v1beta4'>;
}
declare module 'googleapis/v1.js' {
  declare module.exports: $Exports<'googleapis/v1'>;
}
declare module 'googleapis/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/v1beta1'>;
}
declare module 'googleapis/v1beta2.js' {
  declare module.exports: $Exports<'googleapis/v1beta2'>;
}
declare module 'googleapis/v1.js' {
  declare module.exports: $Exports<'googleapis/v1'>;
}
declare module 'googleapis/v1.js' {
  declare module.exports: $Exports<'googleapis/v1'>;
}
declare module 'googleapis/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/v1beta1'>;
}
declare module 'googleapis/v1beta2.js' {
  declare module.exports: $Exports<'googleapis/v1beta2'>;
}
declare module 'googleapis/v1.js' {
  declare module.exports: $Exports<'googleapis/v1'>;
}
declare module 'googleapis/v1beta3.js' {
  declare module.exports: $Exports<'googleapis/v1beta3'>;
}
declare module 'googleapis/v2.js' {
  declare module.exports: $Exports<'googleapis/v2'>;
}
declare module 'googleapis/v1.js' {
  declare module.exports: $Exports<'googleapis/v1'>;
}
declare module 'googleapis/v1.js' {
  declare module.exports: $Exports<'googleapis/v1'>;
}
declare module 'googleapis/v1.js' {
  declare module.exports: $Exports<'googleapis/v1'>;
}
declare module 'googleapis/v3.js' {
  declare module.exports: $Exports<'googleapis/v3'>;
}
declare module 'googleapis/v3.js' {
  declare module.exports: $Exports<'googleapis/v3'>;
}
declare module 'googleapis/v1.js' {
  declare module.exports: $Exports<'googleapis/v1'>;
}
declare module 'googleapis/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/v1beta1'>;
}
declare module 'googleapis/v1.js' {
  declare module.exports: $Exports<'googleapis/v1'>;
}
declare module 'googleapis/apirequest.js' {
  declare module.exports: $Exports<'googleapis/apirequest'>;
}
declare module 'googleapis/authclient.js' {
  declare module.exports: $Exports<'googleapis/authclient'>;
}
declare module 'googleapis/computeclient.js' {
  declare module.exports: $Exports<'googleapis/computeclient'>;
}
declare module 'googleapis/jwtclient.js' {
  declare module.exports: $Exports<'googleapis/jwtclient'>;
}
declare module 'googleapis/loginticket.js' {
  declare module.exports: $Exports<'googleapis/loginticket'>;
}
declare module 'googleapis/oauth2client.js' {
  declare module.exports: $Exports<'googleapis/oauth2client'>;
}
declare module 'googleapis/discovery.js' {
  declare module.exports: $Exports<'googleapis/discovery'>;
}
declare module 'googleapis/generator_utils.js' {
  declare module.exports: $Exports<'googleapis/generator_utils'>;
}
declare module 'googleapis/generator.js' {
  declare module.exports: $Exports<'googleapis/generator'>;
}
declare module 'googleapis/googleapis.js' {
  declare module.exports: $Exports<'googleapis/googleapis'>;
}
declare module 'googleapis/pemverifier.js' {
  declare module.exports: $Exports<'googleapis/pemverifier'>;
}
declare module 'googleapis/transporters.js' {
  declare module.exports: $Exports<'googleapis/transporters'>;
}
declare module 'googleapis/utils.js' {
  declare module.exports: $Exports<'googleapis/utils'>;
}
declare module 'googleapis/generate.js' {
  declare module.exports: $Exports<'googleapis/generate'>;
}
declare module 'googleapis/api-endpoint.js' {
  declare module.exports: $Exports<'googleapis/api-endpoint'>;
}
declare module 'googleapis/method-partial.js' {
  declare module.exports: $Exports<'googleapis/method-partial'>;
}
declare module 'googleapis/resource-partial.js' {
  declare module.exports: $Exports<'googleapis/resource-partial'>;
}
