// flow-typed signature: 47ccf911cb684e4676506c72a53bc12b
// flow-typed version: <<STUB>>/react-native-calendar-events_v^1.0.0/flow_v0.30.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-calendar-events'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-calendar-events' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-calendar-events/RNCalendarEvents.ios' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-calendar-events/RNCalendarEvents.ios.js' {
  declare module.exports: $Exports<'react-native-calendar-events/RNCalendarEvents.ios'>;
}
